version: '3'

vars:
  MODULE_NAME: surfin
  BUILD_OUTPUT_DIR: dist
  WEATHER_TASKFILE_PATH: example/weather/Taskfile.yaml

tasks:
  # Run all tests in the repository.
  test:
    desc: "Run all tests in the repository."
    cmds:
      - go test ./test/... -v -count=1

  # Clean up Go module dependencies.
  mod-tidy:
    desc: "Clean up Go module dependencies (add missing and remove unused modules)."
    cmds:
      - go clean -modcache
      - go clean -cache -testcache
      - go mod tidy

  weather:
    desc: "Tasks for the example/weather application."
    cmds:
      - sh -c 'task --taskfile "{{.WEATHER_TASKFILE_PATH}}" "$@"' _ {{.CLI_ARGS}}

  clean:
    desc: "Remove all build artifacts."
    cmds:
      - rm -rf ./{{.BUILD_OUTPUT_DIR}}
